import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
    content: [
        "./pages/**/*.{ts,tsx}",
            "./components/**/*.{ts,tsx}",
                "./app/**/*.{ts,tsx}",
                  ],
                    theme: {
                        extend: {
                              colors: {
                                      "rioave": {
                                                green: {
                                                            DEFAULT: "#006437",
                                                                        light: "#008A4C",
                                                                                    dark: "#004A28",
                                                                                                50: "#E6F4ED",
                                                                                                            100: "#C0E3D0",
                                                                                                                      },
                                                                                                                                white: "#FFFFFF",
                                                                                                                                          gray: "#F5F5F5",
                                                                                                                                                  },
                                                                                                                                                          border: "hsl(var(--border))",
                                                                                                                                                                  input: "hsl(var(--input))",
                                                                                                                                                                          ring: "hsl(var(--ring))",
                                                                                                                                                                                  background: "hsl(var(--background))",
                                                                                                                                                                                          foreground: "hsl(var(--foreground))",
                                                                                                                                                                                                  primary: {
                                                                                                                                                                                                            DEFAULT: "hsl(var(--primary))",
                                                                                                                                                                                                                      foreground: "hsl(var(--primary-foreground))",
                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                      secondary: {
                                                                                                                                                                                                                                                DEFAULT: "hsl(var(--secondary))",
                                                                                                                                                                                                                                                          foreground: "hsl(var(--secondary-foreground))",
                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                          destructive: {
                                                                                                                                                                                                                                                                                    DEFAULT: "hsl(var(--destructive))",
                                                                                                                                                                                                                                                                                              foreground: "hsl(var(--destructive-foreground))",
                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                              muted: {
                                                                                                                                                                                                                                                                                                                        DEFAULT: "hsl(var(--muted))",
                                                                                                                                                                                                                                                                                                                                  foreground: "hsl(var(--muted-foreground))",
                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                  accent: {
                                                                                                                                                                                                                                                                                                                                                            DEFAULT: "hsl(var(--accent))",
                                                                                                                                                                                                                                                                                                                                                                      foreground: "hsl(var(--accent-foreground))",
                                                                                                                                                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                                                                                                                                                      card: {
                                                                                                                                                                                                                                                                                                                                                                                                DEFAULT: "hsl(var(--card))",
                                                                                                                                                                                                                                                                                                                                                                                                          foreground: "hsl(var(--card-foreground))",
                                                                                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                                                                              borderRadius: {
                                                                                                                                                                                                                                                                                                                                                                                                                                      lg: "var(--radius)",
                                                                                                                                                                                                                                                                                                                                                                                                                                              md: "calc(var(--radius) - 2px)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                      sm: "calc(var(--radius) - 4px)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    plugins: [require("tailwindcss-animate")],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                    export default config;