export function RioAveLogo({ size = 80 }: { size?: number }) {
      return (
          <div
                className="flex flex-col items-center"
                      style={{ width: size }}
                            role="img"
                                  aria-label="Rio Ave FC"
                                      >
                                            <svg
                                                    viewBox="0 0 80 90"
                                                            fill="none"
                                                                    xmlns="http://www.w3.org/2000/svg"
                                                                            width={size}
                                                                                    height={size * 1.1}
                                                                                          >
                                                                                                  {/* Escudo */}
                                                                                                          <path
                                                                                                                    d="M40 2 L76 16 L76 52 C76 70 60 83 40 89 C20 83 4 70 4 52 L4 16 Z"
                                                                                                                              fill="white"
                                                                                                                                        opacity="0.95"
                                                                                                                                                />
                                                                                                                                                        <path
                                                                                                                                                                  d="M40 6 L72 19 L72 52 C72 68 57 80 40 85 C23 80 8 68 8 52 L8 19 Z"
                                                                                                                                                                            fill="#006437"
                                                                                                                                                                                    />
                                                                                                                                                                                            {/* Faixa branca central */}
                                                                                                                                                                                                    <path
                                                                                                                                                                                                              d="M8 42 L72 42 L72 52 C72 68 57 80 40 85 C23 80 8 68 8 52 Z"
                                                                                                                                                                                                                        fill="white"
                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                        {/* Texto superior */}
                                                                                                                                                                                                                                                <text
                                                                                                                                                                                                                                                          x="40"
                                                                                                                                                                                                                                                                    y="36"
                                                                                                                                                                                                                                                                              textAnchor="middle"
                                                                                                                                                                                                                                                                                        fill="white"
                                                                                                                                                                                                                                                                                                  fontSize="10"
                                                                                                                                                                                                                                                                                                            fontWeight="bold"
                                                                                                                                                                                                                                                                                                                      fontFamily="system-ui, sans-serif"
                                                                                                                                                                                                                                                                                                                                letterSpacing="1"
                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                  RIO AVE
                                                                                                                                                                                                                                                                                                                                                          </text>
                                                                                                                                                                                                                                                                                                                                                                  <text
                                                                                                                                                                                                                                                                                                                                                                            x="40"
                                                                                                                                                                                                                                                                                                                                                                                      y="48"
                                                                                                                                                                                                                                                                                                                                                                                                textAnchor="middle"
                                                                                                                                                                                                                                                                                                                                                                                                          fill="white"
                                                                                                                                                                                                                                                                                                                                                                                                                    fontSize="8"
                                                                                                                                                                                                                                                                                                                                                                                                                              fontFamily="system-ui, sans-serif"
                                                                                                                                                                                                                                                                                                                                                                                                                                        opacity="0.9"
                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                          F.C.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* Texto inferior (na faixa branca) */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <text
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            x="40"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      y="68"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                textAnchor="middle"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          fill="#006437"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fontSize="8"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              fontWeight="bold"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        fontFamily="system-ui, sans-serif"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          1939
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </svg>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
}