"use client";

import { useState } from "react";
import {
  Card,
    CardContent,
      CardDescription,
        CardHeader,
          CardTitle,
          } from "@/components/ui/card";
          import { LoginForm } from "@/components/auth/LoginForm";
          import { OtpForm } from "@/components/auth/OtpForm";
          import { RioAveLogo } from "@/components/shared/RioAveLogo";

          type AuthStep = "phone" | "otp";

          export function LoginPageClient() {
            const [step, setStep] = useState<AuthStep>("phone");
              const [phone, setPhone] = useState("");

                const handleOtpSent = (formattedPhone: string) => {
                    setPhone(formattedPhone);
                        setStep("otp");
                          };

                            const handleBack = () => {
                                setStep("phone");
                                    setPhone("");
                                      };

                                        return (
                                            <main className="min-h-screen flex flex-col items-center justify-center bg-gradient-to-b from-rioave-green-dark via-rioave-green to-rioave-green-light px-4 py-8 relative overflow-hidden">
                                                  {/* Padrão decorativo de fundo */}
                                                        <div
                                                                className="absolute inset-0 opacity-5 pointer-events-none"
                                                                        aria-hidden="true"
                                                                                style={{
                                                                                          backgroundImage: `radial-gradient(circle at 25% 25%, white 1px, transparent 1px), radial-gradient(circle at 75% 75%, white 1px, transparent 1px)`,
                                                                                                    backgroundSize: "40px 40px",
                                                                                                            }}
                                                                                                                  />

                                                                                                                        <div className="relative z-10 w-full max-w-sm space-y-8">
                                                                                                                                {/* Logo e identidade */}
                                                                                                                                        <div className="flex flex-col items-center space-y-4">
                                                                                                                                                  <RioAveLogo size={90} />
                                                                                                                                                            <div className="text-center">
                                                                                                                                                                        <h1 className="text-3xl font-bold text-white tracking-tight">
                                                                                                                                                                                      Onda Verde
                                                                                                                                                                                                  </h1>
                                                                                                                                                                                                              <p className="text-green-100 text-sm mt-1 font-medium tracking-wide uppercase">
                                                                                                                                                                                                                            Rio Ave FC · Área de Sócios
                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                  {/* Card principal */}
                                                                                                                                                                                                                                                                          <Card className="shadow-2xl border-0 bg-white/98 backdrop-blur-sm">
                                                                                                                                                                                                                                                                                    <CardHeader className="space-y-1 pb-4 text-center">
                                                                                                                                                                                                                                                                                                <CardTitle className="text-xl font-bold text-rioave-green-dark">
                                                                                                                                                                                                                                                                                                              {step === "phone" ? "Bem-vindo de volta" : "Verificação SMS"}
                                                                                                                                                                                                                                                                                                                          </CardTitle>
                                                                                                                                                                                                                                                                                                                                      <CardDescription className="text-sm">
                                                                                                                                                                                                                                                                                                                                                    {step === "phone"
                                                                                                                                                                                                                                                                                                                                                                    ? "Insere o teu número para aceder"
                                                                                                                                                                                                                                                                                                                                                                                    : "Insere o código que recebeste por SMS"}
                                                                                                                                                                                                                                                                                                                                                                                                </CardDescription>
                                                                                                                                                                                                                                                                                                                                                                                                          </CardHeader>

                                                                                                                                                                                                                                                                                                                                                                                                                    <CardContent className="pb-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                {/* Barra de progresso */}
                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="flex items-center gap-2 mb-6" aria-hidden="true">
                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className={`h-1.5 flex-1 rounded-full transition-all duration-500 ${
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            step === "phone"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ? "bg-rioave-green"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    : "bg-rioave-green-light"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className={`h-1.5 flex-1 rounded-full transition-all duration-500 ${
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  step === "otp" ? "bg-rioave-green" : "bg-gray-200"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {step === "phone" ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <LoginForm onOtpSent={handleOtpSent} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <OtpForm phone={phone} onBack={handleBack} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </CardContent>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </Card>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* Footer */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="text-center text-xs text-green-100/70">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        © {new Date().getFullYear()} Rio Ave FC · Todos os direitos reservados
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }